WORKFLOW_PENDING = "PENDING"
WORKFLOW_RUNNING = "RUNNING"
WORKFLOW_SUCCESS = "SUCCESS"
WORKFLOW_FAILED = "FAILED"

STEP_PENDING = "PENDING"
STEP_RUNNING = "RUNNING"
STEP_SUCCESS = "SUCCESS"
STEP_FAILED = "FAILED"