# riya_engine/runtime/event_types.py

INPUT_RECEIVED = "INPUT_RECEIVED"

TEXT_CLEANED = "TEXT_CLEANED"

COMMAND_SPLIT = "COMMAND_SPLIT"

ENTITY_NORMALIZED = "ENTITY_NORMALIZED"

INTENT_DETECTED = "INTENT_DETECTED"

PLAN_CREATED = "PLAN_CREATED"

MEMORY_UPDATED = "MEMORY_UPDATED"

TASK_CREATED = "TASK_CREATED"

TASK_STARTED = "TASK_STARTED"

TASK_COMPLETED = "TASK_COMPLETED"

TASK_FAILED = "TASK_FAILED"

WORKFLOW_STARTED = "WORKFLOW_STARTED"

WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"

WORKFLOW_FAILED = "WORKFLOW_FAILED"

STEP_STARTED = "STEP_STARTED"

STEP_COMPLETED = "STEP_COMPLETED"

STEP_FAILED = "STEP_FAILED"