# runtime/events.py
# Event definitions for the Riya runtime
# riya_engine/runtime/events.py

class Events:
    USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED"

    INTENT_DETECTED = "INTENT_DETECTED"

    PLAN_CREATED = "PLAN_CREATED"

    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

    MEMORY_UPDATED = "MEMORY_UPDATED"

    STATE_CHANGED = "STATE_CHANGED"

    SYSTEM_ERROR = "SYSTEM_ERROR"

    WORKFLOW_STARTED = "WORKFLOW_STARTED"

    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"

    WORKFLOW_FAILED = "WORKFLOW_FAILED"

    STEP_STARTED = "STEP_STARTED"

    STEP_COMPLETED = "STEP_COMPLETED"

    STEP_FAILED = "STEP_FAILED"